default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.21.0
    hooks:
      - id: pyupgrade
        stages:
          - commit
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.6.1
    hooks:
    - id: reorder-python-imports
      stages:
      - commit
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        stages:
          - commit
  - repo: https://github.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        stages:
          - commit
        additional_dependencies:
          - cohesion==1.0.0
          - flake8-2020==1.5.0
          - flake8-bandit==2.1.2
          - flake8-blind-except==0.1.1
          - flake8-bugbear==20.1.2
          - flake8-builtins==1.4.2
          - flake8-coding==1.3.2
          - flake8-comprehensions==3.2.2
          - flake8-copyright==0.2.2
          - flake8-debugger==3.2.1
          - flake8-docstrings==1.5.0
          - flake8-mutable==1.2.0
          - flake8-pep3101==1.3.0
          - flake8-quotes==2.1.1
          - flake8-logging-format==0.6.0
          - flake8-print==3.1.4
          - flake8-pytest==0.1.3
          - flake8-self==0.2.2
          - flake8-typing-imports==1.5.1
          - pep8-naming==0.9.1
  - repo: local
    hooks:
      - id: dockerlint
        name: dockerlint
        language: docker_image
        entry: hadolint/hadolint hadolint
        files: Dockerfile
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.0
    hooks:
      - id: commitlint
        additional_dependencies:
          - "@commitlint/config-conventional"
        stages:
          - commit-msg
