default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.21.0
    hooks:
      - id: pyupgrade
        stages:
          - commit
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        stages:
          - commit
        additional_dependencies:
          - toml
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        stages:
          - commit
  - repo: https://github.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        stages:
          - commit
        additional_dependencies:
          - cohesion==1.0.0
          - flake8-2020==1.5.0
          - flake8-copyright==0.2.2
          - git+https://github.com/wemake-services/wemake-python-styleguide
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: dockerlint
        name: dockerlint
        language: docker_image
        entry: hadolint/hadolint hadolint
        files: Dockerfile
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.0
    hooks:
      - id: commitlint
        additional_dependencies:
          - "@commitlint/config-conventional"
        stages:
          - commit-msg
