version: "3.6"

services:
  app:
    build:
      context: .
      target: development
    restart: unless-stopped
    image: {{ cookiecutter.project_name }}
    volumes:
      - .:/app
    environment:
      ENV: development

