version: "3.7"

x-settings: &x-settings
  build: .
  restart: unless-stopped
  image: {{ cookiecutter.project_name }}
  volumes:
    - .:/app
  environment:
    ENV: development

services:
  dev:
    <<: *x-settings

  ipython:
    <<: *x-settings
    command: ["ipython"]

  invoke:
    <<: *x-settings
    entrypoint: ["invoke"]
