name: Test
on:
  - push
  - pull_request

jobs:
  test:
    name: ${% raw %}{{ matrix.python-version }}{% endraw %} on {% raw %}${{ matrix.os }}{% endraw %}
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    runs-on: ${% raw %}{{ matrix.os }}{% endraw %}
    steps:
      - name: Checkout source
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: ${% raw %}{{ matrix.python-version }}{% endraw %}
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -e".[test]"
      - name: Run tests
        run: pytest
