{% raw %}{% set data = load_setup_py_data(setup_file="../setup.py", from_recipe_dir=True) %}{% endraw %}

package:
  name: {% raw %}{{ data.get("name") }}{% endraw %}
  version: {% raw %}{{ data.get("version") }}{% endraw %}

source:
  path: ../

build:
  noarch: python
  number: 0
  script: {% raw %}{{ PYTHON }}{% endraw %} -m pip install . -vv

requirements:
  host:
    - python
    - pip

  run:
  {% for package in resolved_packages("host") %}
    - {{ package }}
  {% endfor %}
  
test:
  commands:
    - pytest -m "not srconly"
  imports:
    - {{ cookiecutter.project_slug }}
    - {{ cookiecutter.project_slug }}.__about__
  test:
    - pytest
    - pytest-cov


about:
  home: {% raw %}{{ data["url"] }}{% endraw %}
  license: {% raw %}{{ data["license"] }}{% endraw %}{% if cookiecutter.license != "No license" %}
  license_file: LICENSE{% endif %}
  summary: {% raw %}{{ data["description"] }}{% endraw %}
  doc_url: {% raw %}{{ data["project_urls"]["Documentation"] }}{% endraw %}
  dev_url: {% raw %}{{ data["project_urls"]["Source"] }}{% endraw %}

extra:
  recipe-maintainers:
    - {{ cookiecutter.author_name }} <{{ cookiecutter.author_email }}>
