{% raw %}{% set data = load_setup_py_data(setup_file="../setup.py", from_recipe_dir=True) %}{% endraw %}

package:
  name: {% raw %}{{ data.get("name") }}{% endraw %}
  version: {% raw %}{{ data.get("version") }}{% endraw %}

source:
  path: ../

build:
  script: {% raw %}{{ PYTHON }}{% endraw %} -m pip install . -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
  
  test:
    - pytest
    - pytest-cov

about:
  home: {% raw %}{{ data["url"] }}{% endraw %}
  license: {% raw %}{{ data["license"] }}{% endraw %}
  license_file: LICENSE
  summary: {% raw %}{{ data["description"] }}{% endraw %}
  doc_url: {% raw %}{{ data["project_urls"]["Documentation"] }}{% endraw %}
  dev_url: {% raw %}{{ data["project_urls"]["Source"] }}{% endraw %}
