name: {{ cookiecutter.project_name }}-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3
  - ipython
  - pytest
  - pytest-cov
  - black
  - rope
  - flake8
  - flake8-builtins
  - flake8-mutable
  - flake8-docstrings
  - pep8-naming
  - pre-commit
  - pip
  - pip:
      - flake8-bandit
      - flake8-bugbear
      - flake8-logging-format
      - flake8-print
      - -e..
